//! Path of Building's data files, written straight from the game files in the
//! layout repoe-fork publishes as pob-data
//! (<https://repoe-fork.github.io/pob-data/>): one JSON per file PoB keeps
//! under `src/Data/`, holding the Lua table that file evaluates to.
//!
//! Each module ports one of PoB's export scripts (`src/Export/Scripts/*.lua`)
//! and reads the same tables through the shared [`Ctx`]. What PoB writes by
//! hand — skill stat maps, the mod parser cache, unique and rare lists, trade
//! site ids — is not in the game files and is listed in the report instead.

pub mod lua;
pub mod modules;
pub mod statdesc;
pub mod text;

use crate::data_export::{json, Ctx, DataExportOptions};
use crate::export::ExportStatus;
use crate::settings::Game;
use std::cell::RefCell;
use std::collections::HashMap;
use std::path::PathBuf;
use std::rc::Rc;
use std::sync::mpsc::Sender;

pub use lua::{Lua, Table};

/// Every module, in the order they run.
pub fn registry() -> Vec<crate::data_export::modules::Module> {
    modules::registry()
}

pub fn module_names() -> Vec<&'static str> {
    registry().into_iter().map(|m| m.name).collect()
}

/// Runs the export, reporting progress the way `data_export::run` does.
pub fn run(
    files: crate::data_export::source::GameFiles,
    schema: crate::dat::schema::Schema,
    is_poe2: bool,
    out: PathBuf,
    options: DataExportOptions,
    tx: Sender<ExportStatus>,
) {
    let game = Game::from_is_poe2(is_poe2);
    let not_exported = json::J::Obj(
        not_game_data(game).iter().map(|(file, why)| (file.to_string(), json::text(why))).collect(),
    );
    let kind = crate::data_export::RunKind {
        file_suffix: "",
        unit: "PoB data modules",
        extra_report: vec![("not_game_data".to_string(), not_exported)],
    };
    crate::data_export::run_with(registry(), kind, files, schema, is_poe2, out, options, tx);
}

/// Files PoB ships that no game file holds, with where they come from.
pub fn not_game_data(game: Game) -> &'static [(&'static str, &'static str)] {
    const SHARED: [(&str, &str); 6] = [
        ("ModCache", "PoB's mod parser run over every mod line"),
        ("SkillStatMap", "PoB's own map from skill stats to its modifiers"),
        ("Rares", "rare item templates PoB writes by hand"),
        ("Uniques", "unique items PoB writes by hand; the game keeps them on the server"),
        ("QueryMods", "the official trade site's stat ids, fetched from the site"),
        ("TradeSiteStats", "the official trade site's stat list, fetched from the site"),
    ];
    const POE2: [(&str, &str); 11] = [
        SHARED[0],
        SHARED[1],
        SHARED[2],
        SHARED[3],
        SHARED[4],
        SHARED[5],
        ("QuestRewards", "quest rewards PoB writes by hand"),
        ("ModMap", "map mods PoB writes by hand"),
        ("ClusterJewels", "a PoE 1 leftover in PoB's PoE 2 data; PoE 2 has no cluster jewels"),
        ("Bosses, BossSkills", "PoE 1's files, which PoB ships for PoE 2 with its boss exporter switched off"),
        ("TimelessJewelData/LegionTradeIds, NodeIndexMapping", "trade site ids and PoB's own node numbering"),
    ];
    const POE1: [(&str, &str); 13] = [
        SHARED[0],
        SHARED[1],
        SHARED[2],
        SHARED[3],
        SHARED[4],
        SHARED[5],
        ("ModMap", "map mods PoB writes by hand"),
        ("ModFoulbornMap", "built from PoB's hand-written unique list"),
        ("DelveDropOnly", "delve drop restrictions PoB writes by hand"),
        ("IncursionDropOnly", "incursion drop restrictions PoB writes by hand"),
        ("Vestigial", "maps mods to PoB's hand-written unique list"),
        ("TimelessJewelData/*.zip", "seed lookup tables generated by walking the client, not in the game files"),
        ("TimelessJewelData/LegionTradeIds, NodeIndexMapping, AbyssNotableNames", "trade site ids and PoB's own numbering"),
    ];
    match game {
        Game::Poe2 => &POE2,
        Game::Poe1 => &POE1,
    }
}

/// State PoB's exporters share across scripts, kept for one run.
#[derive(Default)]
pub struct Caches {
    describers: RefCell<HashMap<String, Rc<statdesc::Descriptors>>>,
}

/// `loadStatFile(first, …)`: the describer for one description file, with any
/// further files laid over it the way PoE 1's exporter appends them. Names
/// carry the game's extension (`stat_descriptions.csd`,
/// `stat_descriptions.txt`). Cached for the run.
pub fn describer(ctx: &Ctx, names: &[&str]) -> Rc<statdesc::Descriptors> {
    let key = names.join("|").to_ascii_lowercase();
    if let Some(hit) = ctx.pob.describers.borrow().get(&key) {
        return Rc::clone(hit);
    }
    let game = game(ctx);
    let fetch = |path: &str| crate::dat::relational::FileSource::fetch(ctx.files, path);
    let mut descriptors = statdesc::Descriptors::load(game, names[0], &fetch);
    for extra in &names[1..] {
        descriptors.append(extra, &fetch);
    }
    let descriptors = Rc::new(descriptors);
    ctx.pob.describers.borrow_mut().insert(key, Rc::clone(&descriptors));
    descriptors
}

/// The game this run reads.
pub fn game(ctx: &Ctx) -> Game {
    Game::from_is_poe2(ctx.rr.is_poe2)
}

/// Writes one PoB data file, `name` being its path under `src/Data/` without
/// the extension (`Bases/amulet`, `ModItem`).
pub fn write(ctx: &Ctx, name: &str, value: impl Into<Lua>) -> Result<(), String> {
    lua::write(ctx.out, name, &value.into())
}

/// A game text file decoded as PoB reads it (`convertUTF16to8`), or `None`
/// when the install does not have it.
pub fn read_text(ctx: &Ctx, path: &str) -> Option<String> {
    crate::dat::relational::FileSource::fetch(ctx.files, path).map(|b| statdesc::decode_utf16(&b))
}
